name: The Informal System

on:
  push:
    branches:
      - main

jobs:
  guide:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: cache .cargo directory
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: cargo-dir
          restore-keys: |
            cargo-dir

      - name: Install mdbook
        uses: actions-rs/install@v0.1
        with:
          crate: mdbook
          version: latest
          use-tool-cache: true

      - name: Install mdbook-mermaid
        uses: actions-rs/install@v0.1
        with:
          crate: mdbook-mermaid
          version: latest
          use-tool-cache: true

      - name: Install mdbook-toc
        uses: actions-rs/install@v0.1
        with:
          crate: mdbook-toc
          version: latest
          use-tool-cache: true

      - name: Build guide
        run: |
          mdbook build

      # Only deploy guide when pushing to main
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
